"""Newsletter generation for EV Pulse monthly digest."""

import os
import json
import logging
from datetime import datetime
from openai import OpenAI

from .db import get_connection

logger = logging.getLogger(__name__)


def generate_newsletter_html(month: str = None) -> str:
    """Generate an HTML newsletter for the given month."""
    if not month:
        today = datetime.now()
        month = today.strftime("%Y-%m")

    # Get articles for this month
    articles = _get_month_articles(month)
    if not articles:
        return _empty_newsletter(month)

    # Try LLM newsletter generation
    html = _llm_newsletter(articles, month)
    if html:
        return html

    # Fallback: structured HTML newsletter
    return _structured_newsletter(articles, month)


def _get_month_articles(month: str) -> list[dict]:
    """Get relevant articles for a month (relevance >= 3)."""
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT * FROM articles 
               WHERE collected_at LIKE ? || '%'
               AND relevance_score >= 3
               ORDER BY relevance_score DESC""",
            (month,)
        ).fetchall()
        return [dict(r) for r in rows]


def _empty_newsletter(month: str) -> str:
    """HTML for when there are no articles."""
    return f"""
    <html>
    <body style="font-family: -apple-system, sans-serif; background: #f5f5f5; padding: 40px;">
        <div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; padding: 40px; text-align: center;">
            <h1 style="color: #6366f1;">⚡ EV Charging Pulse</h1>
            <h2>{month}</h2>
            <p style="color: #666;">No relevant EV charging articles found for this month.</p>
            <p style="color: #999; font-size: 12px;">Generated by EV Pulse</p>
        </div>
    </body>
    </html>
    """


def _llm_newsletter(articles: list[dict], month: str) -> str | None:
    """Generate newsletter using LLM."""
    try:
        api_key = os.getenv('OPENAI_API_KEY') or os.getenv('LLM_API_KEY')
        if not api_key:
            return None

        client = OpenAI(
            api_key=api_key,
            base_url=os.getenv('LLM_BASE_URL', 'https://api.openai.com/v1')
        )

        # Prepare article summaries
        article_list = []
        for a in articles[:40]:
            article_list.append(
                f"[{a['region']}] [{a.get('category', 'other')}] "
                f"Score {a['relevance_score']}: {a['title']}\n"
                f"{a.get('summary', 'No summary')}\n"
                f"URL: {a['url']}"
            )

        articles_text = "\n\n".join(article_list)

        prompt = f"""Generate an HTML email newsletter for EV Charging Pulse ({month}).

Articles collected from emerging markets:
{articles_text}

Create a professional HTML newsletter with this structure:
- Dark header with "⚡ EV Charging Pulse" title
- Key Takeaways section (3-5 bullet points)
- Country-by-country sections with article links
- Cross-border insights
- Clean, professional design with inline CSS

Return ONLY the HTML, no markdown code blocks. Use inline styles for email compatibility."""

        response = client.chat.completions.create(
            model=os.getenv('LLM_MODEL', 'gpt-4o-mini'),
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=4000
        )
        return response.choices[0].message.content

    except Exception as e:
        logger.error(f"LLM newsletter generation failed: {e}")
        return None


def _structured_newsletter(articles: list[dict], month: str) -> str:
    """Fallback structured HTML newsletter."""
    # Group by region
    regions = {}
    for a in articles:
        r = a['region']
        if r not in regions:
            regions[r] = []
        regions[r].append(a)

    region_sections = ""
    for region, region_articles in sorted(regions.items()):
        items = ""
        for a in region_articles[:5]:
            items += f"""
            <tr>
                <td style="padding: 8px 0; border-bottom: 1px solid #eee;">
                    <a href="{a['url']}" style="color: #333; text-decoration: none; font-weight: 500;">
                        {a['title']}
                    </a>
                    <br>
                    <span style="color: #666; font-size: 13px;">{a.get('summary', '')[:150]}</span>
                    <br>
                    <span style="color: #999; font-size: 11px;">{a['source']} | Score: {a['relevance_score']}</span>
                </td>
            </tr>
            """

        region_names = {
            'korea': '🇰🇷 South Korea',
            'uae': '🇦🇪 UAE / Middle East',
            'southeast_asia': '🌏 Southeast Asia',
            'japan': '🇯🇵 Japan',
            'australia': '🇦🇺 Australia',
            'taiwan': '🇹🇼 Taiwan',
            'africa': '🌍 Africa / South Africa',
            'brazil': '🇧🇷 Brazil',
            'mexico': '🇲🇽 Mexico / Central America',
        }

        region_sections += f"""
        <tr>
            <td style="padding: 24px 0 12px; border-bottom: 2px solid #6366f1;">
                <h2 style="margin: 0; color: #1a1a2e; font-size: 18px;">
                    {region_names.get(region, region.title())}
                </h2>
            </td>
        </tr>
        {items}
        """

    return f"""
    <html>
    <body style="font-family: -apple-system, sans-serif; background: #f5f5f5; padding: 40px; margin: 0;">
        <div style="max-width: 600px; margin: 0 auto;">
            <!-- Header -->
            <div style="background: linear-gradient(135deg, #6366f1, #818cf8); border-radius: 12px 12px 0 0; padding: 32px; text-align: center;">
                <h1 style="margin: 0; color: white; font-size: 24px;">⚡ EV Charging Pulse</h1>
                <p style="margin: 8px 0 0; color: rgba(255,255,255,0.8); font-size: 14px;">
                    Emerging Markets Monthly Briefing — {month}
                </p>
            </div>

            <!-- Content -->
            <div style="background: white; border-radius: 0 0 12px 12px; padding: 32px;">
                <p style="color: #666; font-size: 14px; margin-bottom: 24px;">
                    This month we tracked <strong>{len(articles)}</strong> relevant articles across 
                    <strong>{len(regions)}</strong> regions.
                </p>

                <table width="100%" cellpadding="0" cellspacing="0">
                    {region_sections}
                </table>

                <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee; text-align: center;">
                    <p style="color: #999; font-size: 12px;">
                        Generated by EV Pulse on {datetime.now().strftime('%Y-%m-%d')}<br>
                        <a href="#" style="color: #6366f1;">View Full Dashboard</a>
                    </p>
                </div>
            </div>
        </div>
    </body>
    </html>
    """


def get_newsletter_text(month: str = None) -> str:
    """Generate plain text version of newsletter."""
    if not month:
        month = datetime.now().strftime("%Y-%m")

    articles = _get_month_articles(month)
    if not articles:
        return f"EV Charging Pulse — {month}\n\nNo relevant articles found."

    regions = {}
    for a in articles:
        r = a['region']
        if r not in regions:
            regions[r] = []
        regions[r].append(a)

    lines = [
        f"⚡ EV Charging Pulse — {month}",
        f"Emerging Markets Monthly Briefing",
        f"",
        f"This month: {len(articles)} articles across {len(regions)} regions",
        f"",
        "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
        ""
    ]

    region_names = {
        'korea': '🇰🇷 South Korea',
        'uae': '🇦🇪 UAE / Middle East',
        'southeast_asia': '🌏 Southeast Asia',
        'japan': '🇯🇵 Japan',
        'australia': '🇦🇺 Australia',
        'taiwan': '🇹🇼 Taiwan',
        'africa': '🌍 Africa / South Africa',
        'brazil': '🇧🇷 Brazil',
        'mexico': '🇲🇽 Mexico / Central America',
    }

    for region, region_articles in sorted(regions.items()):
        lines.append(f"▸ {region_names.get(region, region.title())}")
        for a in region_articles[:5]:
            lines.append(f"  • {a['title']}")
            lines.append(f"    {a.get('summary', '')[:120]}")
            lines.append(f"    {a['url']}")
            lines.append("")
        lines.append("")

    lines.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    lines.append(f"Generated by EV Pulse | {datetime.now().strftime('%Y-%m-%d')}")

    return "\n".join(lines)
