"""Monthly report generation using LLM."""

import os
import json
import logging
from datetime import datetime
from openai import OpenAI

from .db import get_articles, insert_report

logger = logging.getLogger(__name__)


def generate_monthly_report(month: str = None) -> str:
    """Generate a monthly report for the given month (YYYY-MM)."""
    if not month:
        today = datetime.now()
        month = today.strftime("%Y-%m")

    # Get articles for this month
    articles = _get_month_articles(month)
    if not articles:
        return f"No articles found for {month}."

    # Try LLM report generation
    report = _llm_report(articles, month)
    if report:
        insert_report(month, report, len(articles))
        return report

    # Fallback: structured text report
    report = _structured_report(articles, month)
    insert_report(month, report, len(articles))
    return report


def _get_month_articles(month: str) -> list[dict]:
    """Get articles collected in a given month, relevance >= 3."""
    from .db import get_connection
    with get_connection() as conn:
        rows = conn.execute(
            """SELECT * FROM articles 
               WHERE collected_at LIKE ? || '%'
               AND relevance_score >= 3
               ORDER BY relevance_score DESC""",
            (month,)
        ).fetchall()
        return [dict(r) for r in rows]


def _llm_report(articles: list[dict], month: str) -> str | None:
    """Generate report using LLM."""
    try:
        api_key = os.getenv('OPENAI_API_KEY') or os.getenv('LLM_API_KEY')
        if not api_key:
            return None

        client = OpenAI(
            api_key=api_key,
            base_url=os.getenv('LLM_BASE_URL', 'https://api.openai.com/v1')
        )

        # Prepare article summaries for LLM
        article_list = []
        for a in articles[:50]:  # Cap at 50 for token limits
            article_list.append(
                f"- [{a['region']}] [{a.get('category', 'other')}] "
                f"Score {a['relevance_score']}: {a['title']}\n"
                f"  {a.get('summary', 'No summary')}"
            )

        articles_text = "\n".join(article_list)

        prompt = f"""Generate a monthly EV Charging Intelligence Report for {month}.

These articles were collected from emerging markets:
Korea, UAE/Middle East, Southeast Asia, Japan, Australia, Taiwan, Africa, Brazil, Mexico.

Articles (sorted by relevance):
{articles_text}

Create a structured report in this EXACT format (Markdown):

# EV Charging Pulse — {month}

## Key Takeaways
(3-5 bullet points of the most important developments)

## By Region

### Korea
(0-3 items, each: **Title** — one-line summary. [Source](url))

### UAE / Middle East
(same format)

### Southeast Asia
(same format)

### Japan
(same format)

### Australia
(same format)

### Taiwan
(same format)

### Africa / South Africa
(same format)

### Brazil
(same format)

### Mexico / Central America
(same format)

(Skip regions with no relevant items)

## Cross-Border Insights
(2-3 observations about trends spanning multiple regions)

## Data Points
(Key numbers: installation counts, investment amounts, pricing changes)

## Next Month Watch
(What to watch for in the coming month)

---
*Generated by EV Pulse on {datetime.now().strftime('%Y-%m-%d')}*
*Based on {len(articles)} relevant articles from {len(set(a['region'] for a in articles))} regions*
"""

        response = client.chat.completions.create(
            model=os.getenv('LLM_MODEL', 'gpt-4o-mini'),
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3,
            max_tokens=3000
        )
        return response.choices[0].message.content

    except Exception as e:
        logger.error(f"LLM report generation failed: {e}")
        return None


def _structured_report(articles: list[dict], month: str) -> str:
    """Fallback structured report without LLM."""
    regions = {}
    for a in articles:
        r = a['region']
        if r not in regions:
            regions[r] = []
        regions[r].append(a)

    lines = [
        f"# EV Charging Pulse — {month}",
        "",
        f"*Generated on {datetime.now().strftime('%Y-%m-%d')} | {len(articles)} articles*",
        "",
        "## Articles by Region",
        ""
    ]

    for region, region_articles in sorted(regions.items()):
        lines.append(f"### {region.title()}")
        for a in region_articles[:5]:
            lines.append(f"- **{a['title']}** ({a.get('category', 'other')})")
            lines.append(f"  {a.get('summary', 'No summary')}")
            lines.append(f"  [Source]({a['url']}) — {a['source']}")
            lines.append("")
        lines.append("")

    return "\n".join(lines)
